import { Buffer } from 'node:buffer';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import { buildApp } from '../app';
import type { AppConfig } from '../config/env';

/**
 * Produces the two committed contract artifacts: the OpenAPI document and the generated TypeScript
 * module `@abfall-radar/api-client` reads its transport types from.
 *
 * Both are produced in memory, so the drift test can regenerate them and compare byte-for-byte without
 * writing anything. Nothing here listens on a port or needs a running development server: the
 * application is built in process, and the document is read from `app.swagger()`.
 *
 * The generated module is emitted from the *serialized* document rather than from the in-memory object,
 * so it is derived from exactly the bytes that are committed. The two artifacts therefore cannot
 * disagree about the contract they describe.
 */

const CONTRACT_CONFIG: AppConfig = {
  nodeEnv: 'test',
  logLevel: 'silent',
  // The document only exists when documentation is registered, because @fastify/swagger collects the
  // route schemas through its onRoute hook.
  docsEnabled: true,
};

export const OPENAPI_DOCUMENT_PATH = fileURLToPath(new URL('../../openapi.json', import.meta.url));

export const GENERATED_CLIENT_MODULE_PATH = fileURLToPath(
  new URL('../../../../packages/api-client/src/generated/api.ts', import.meta.url),
);

/**
 * States the rule in the file itself. The drift test is the detector; this is what tells a reader who
 * opens the file why their edit will be rejected. It carries no date, version, or other value that
 * would change between two runs of the same contract.
 */
const GENERATED_MODULE_HEADER = [
  '/**',
  ' * Generated from the AbfallRadar OpenAPI contract. Do not edit this file by hand.',
  ' *',
  ' * Regenerate it with `pnpm --filter @abfall-radar/api generate:contract`, which rebuilds',
  ' * `apps/api/openapi.json` from the runtime route schemas and re-emits this module from those exact',
  ' * bytes. A hand edit is a review blocker rather than a merge conflict: the contract drift test in',
  ' * `apps/api` fails as soon as either committed artifact stops matching what the contract produces.',
  ' *',
  ' * Runtime validation lives in `../contracts`, hand-written and scoped to the untrusted HTTP',
  ' * boundary, because these types vanish at runtime.',
  ' */',
  '',
  '',
].join('\n');

/**
 * The document is serialized with two-space indentation and a trailing newline, matching the
 * repository's formatting conventions for a JSON file. The artifact is excluded from Biome's file set,
 * so this function is the only thing that decides its shape.
 */
export const serializeOpenApiDocument = (document: unknown): string =>
  `${JSON.stringify(document, null, 2)}\n`;

export const buildOpenApiDocumentSource = async (): Promise<string> => {
  const app = await buildApp(CONTRACT_CONFIG);

  try {
    await app.ready();

    return serializeOpenApiDocument(app.swagger());
  } finally {
    await app.close();
  }
};

export const buildGeneratedClientModule = async (documentSource: string): Promise<string> => {
  // A Buffer source is read as UTF-8 and parsed as JSON content, so the generator sees the committed
  // bytes and never resolves a path, a URL, or a configuration file from disk.
  const ast = await openapiTS(Buffer.from(documentSource, 'utf8'), { silent: true });

  return `${GENERATED_MODULE_HEADER}${astToString(ast)}`;
};

export interface ContractArtifacts {
  readonly openApiDocument: string;
  readonly generatedClientModule: string;
}

export const buildContractArtifacts = async (): Promise<ContractArtifacts> => {
  const openApiDocument = await buildOpenApiDocumentSource();

  return {
    openApiDocument,
    generatedClientModule: await buildGeneratedClientModule(openApiDocument),
  };
};
